import { Outfit } from '../types';

export const OUTFITS: Outfit[] = [
  {
    id: 1, emoji: '🧥',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80',
    title: '오버핏 데님 룩', brand: "ZARA x Levi's", price: '₩182,000',
    season: '봄', style: '캐주얼', tags: ['데님', '오버핏', '봄'],
    desc: '클래식한 오버핏 데님 재킷과 와이드 팬츠의 조화. 흰 티셔츠로 깔끔함을 더했습니다.',
    items: [
      { name: '오버핏 데님 재킷', emoji: '🧥', price: '₩89,000' },
      { name: '와이드 데님 팬츠', emoji: '👖', price: '₩59,000' },
      { name: '화이트 베이직 티', emoji: '👕', price: '₩19,000' },
      { name: '화이트 스니커즈', emoji: '👟', price: '₩59,000' },
    ],
  },
  {
    id: 2, emoji: '🌸',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80',
    title: '플로럴 원피스 룩', brand: 'H&M', price: '₩129,000',
    season: '봄', style: '캐주얼', tags: ['원피스', '플로럴', '봄'],
    desc: '화사한 플로럴 패턴의 미디 원피스. 봄 나들이나 브런치 데이트에 완벽한 룩.',
    items: [
      { name: '플로럴 미디 원피스', emoji: '👗', price: '₩79,000' },
      { name: '에스파드리유', emoji: '👡', price: '₩35,000' },
      { name: '위커 백', emoji: '👜', price: '₩29,000' },
    ],
  },
  {
    id: 3, emoji: '🧣',
    image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
    title: '파스텔 레이어드 룩', brand: 'COS', price: '₩198,000',
    season: '봄', style: '미니멀', tags: ['파스텔', '레이어드', '봄'],
    desc: '파스텔 톤의 니트와 와이드 팬츠 조합. 봄의 따뜻한 색감을 담은 미니멀 룩.',
    items: [
      { name: '파스텔 크롭 니트', emoji: '🧶', price: '₩69,000' },
      { name: '아이보리 와이드 팬츠', emoji: '👖', price: '₩79,000' },
      { name: '뮬 슈즈', emoji: '🥿', price: '₩59,000' },
    ],
  },
  {
    id: 4, emoji: '👔',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&q=80',
    title: '봄 포멀 수트 룩', brand: 'Theory', price: '₩320,000',
    season: '봄', style: '포멀', tags: ['수트', '포멀', '봄'],
    desc: '라이트 베이지 수트와 화이트 셔츠의 봄 포멀 룩. 면접이나 비즈니스 미팅에 최적.',
    items: [
      { name: '베이지 슬림핏 재킷', emoji: '🧥', price: '₩159,000' },
      { name: '매칭 드레스 팬츠', emoji: '👖', price: '₩89,000' },
      { name: '화이트 셔츠', emoji: '👔', price: '₩59,000' },
      { name: '브라운 더비 슈즈', emoji: '👞', price: '₩119,000' },
    ],
  },
  {
    id: 5, emoji: '🌿',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400&q=80',
    title: '내추럴 린넨 룩', brand: 'Muji', price: '₩112,000',
    season: '봄', style: '미니멀', tags: ['린넨', '내추럴', '봄'],
    desc: '자연스러운 린넨 소재의 베이지 셔츠와 크림 팬츠. 편안하고 세련된 데일리 룩.',
    items: [
      { name: '오버핏 린넨 셔츠', emoji: '👕', price: '₩45,000' },
      { name: '크림 린넨 팬츠', emoji: '👖', price: '₩49,000' },
      { name: '캔버스 토트백', emoji: '👜', price: '₩29,000' },
    ],
  },
  {
    id: 6, emoji: '☀️',
    image: 'https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=400&q=80',
    title: '리조트 썸머 룩', brand: 'Sundek', price: '₩135,000',
    season: '여름', style: '캐주얼', tags: ['여름', '리조트', '바캉스'],
    desc: '린넨 셔츠와 버뮤다 쇼츠의 리조트 룩. 바닷가나 휴가지에 완벽한 여름 코디.',
    items: [
      { name: '린넨 오픈 셔츠', emoji: '👔', price: '₩49,000' },
      { name: '버뮤다 쇼츠', emoji: '🩳', price: '₩35,000' },
      { name: '슬라이드 샌들', emoji: '🩴', price: '₩25,000' },
      { name: '스트로우 햇', emoji: '👒', price: '₩29,000' },
    ],
  },
  {
    id: 7, emoji: '🎽',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80',
    title: '스트릿 스포티 룩', brand: 'Nike x Supreme', price: '₩198,000',
    season: '여름', style: '스트릿', tags: ['스트릿', '스포티', '여름'],
    desc: '그래픽 티셔츠와 트랙 팬츠의 스트릿 스포티 룩. 편안하면서도 트렌디한 스타일.',
    items: [
      { name: '그래픽 반팔티', emoji: '🎽', price: '₩59,000' },
      { name: '트랙 팬츠', emoji: '👖', price: '₩79,000' },
      { name: '청키 스니커즈', emoji: '👟', price: '₩109,000' },
      { name: '크로스백', emoji: '🎒', price: '₩49,000' },
    ],
  },
  {
    id: 8, emoji: '👗',
    image: 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=400&q=80',
    title: '미니 원피스 룩', brand: 'Zara', price: '₩89,000',
    season: '여름', style: '캐주얼', tags: ['미니', '원피스', '여름'],
    desc: '심플한 화이트 미니 원피스. 여름 데이트나 야외 행사에 청량한 느낌을 줍니다.',
    items: [
      { name: '화이트 미니 원피스', emoji: '👗', price: '₩55,000' },
      { name: '스트랩 샌들', emoji: '👡', price: '₩39,000' },
      { name: '미니 크로스백', emoji: '👜', price: '₩35,000' },
    ],
  },
  {
    id: 9, emoji: '🏄',
    image: 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=400&q=80',
    title: '서핑 비치 룩', brand: 'Quiksilver', price: '₩95,000',
    season: '여름', style: '스포티', tags: ['비치', '서핑', '여름'],
    desc: '래시가드와 보드쇼츠의 비치 스포티 룩. 서핑이나 수영 후에도 멋스러운 스타일.',
    items: [
      { name: '래시가드', emoji: '🏊', price: '₩45,000' },
      { name: '보드쇼츠', emoji: '🩳', price: '₩39,000' },
      { name: '아쿠아 슈즈', emoji: '👟', price: '₩29,000' },
    ],
  },
  {
    id: 10, emoji: '🌺',
    image: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=400&q=80',
    title: '보헤미안 썸머 룩', brand: 'Free People', price: '₩165,000',
    season: '여름', style: '빈티지', tags: ['보헤미안', '빈티지', '여름'],
    desc: '플리츠 맥시스커트와 크롭탑의 보헤미안 룩. 페스티벌이나 야외 파티에 완벽.',
    items: [
      { name: '크롭 레이스 탑', emoji: '👚', price: '₩45,000' },
      { name: '플리츠 맥시스커트', emoji: '👗', price: '₩79,000' },
      { name: '웨지 샌들', emoji: '👡', price: '₩49,000' },
      { name: '레이어드 목걸이', emoji: '📿', price: '₩25,000' },
    ],
  },
  {
    id: 11, emoji: '🌊',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80',
    title: '마린 스트라이프 룩', brand: 'Saint James', price: '₩145,000',
    season: '여름', style: '캐주얼', tags: ['마린', '스트라이프', '여름'],
    desc: '네이비 스트라이프 티셔츠와 화이트 쇼츠의 마린 룩. 항구 마을 감성이 물씬.',
    items: [
      { name: '스트라이프 보트넥 티', emoji: '👕', price: '₩59,000' },
      { name: '화이트 쇼츠', emoji: '🩳', price: '₩45,000' },
      { name: '보트 슈즈', emoji: '👟', price: '₩69,000' },
      { name: '캔버스 토트', emoji: '👜', price: '₩35,000' },
    ],
  },
  {
    id: 12, emoji: '🍂',
    image: 'https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=400&q=80',
    title: '레이어드 니트 룩', brand: 'COS', price: '₩245,000',
    season: '가을', style: '미니멀', tags: ['니트', '레이어드', '가을'],
    desc: '크림색 오버핏 니트와 베이지 트렌치코트의 완벽한 레이어링. 가을의 감성을 담은 룩.',
    items: [
      { name: '오버핏 크림 니트', emoji: '🧶', price: '₩89,000' },
      { name: '베이지 트렌치코트', emoji: '🧥', price: '₩129,000' },
      { name: '슬랙스', emoji: '👖', price: '₩59,000' },
      { name: '로퍼', emoji: '🥿', price: '₩69,000' },
    ],
  },
  {
    id: 13, emoji: '🧤',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&q=80',
    title: '빈티지 레트로 룩', brand: 'Vintage Shop', price: '₩155,000',
    season: '가을', style: '빈티지', tags: ['빈티지', '레트로', '가을'],
    desc: '90년대 감성의 빈티지 청자켓과 플리스 조합. 유니크한 분위기의 가을 코디.',
    items: [
      { name: '빈티지 데님자켓', emoji: '🧥', price: '₩49,000' },
      { name: '플리스 집업', emoji: '🧤', price: '₩39,000' },
      { name: '테이퍼드 팬츠', emoji: '👖', price: '₩45,000' },
      { name: '청키 부츠', emoji: '🥾', price: '₩79,000' },
    ],
  },
  {
    id: 14, emoji: '🎃',
    image: 'https://images.unsplash.com/photo-1548624149-f9b7b0a0b9b4?w=400&q=80',
    title: '어스톤 코디 룩', brand: 'Arket', price: '₩278,000',
    season: '가을', style: '미니멀', tags: ['어스톤', '브라운', '가을'],
    desc: '브라운과 카키의 어스톤 컬러 배합. 자연스럽고 세련된 가을 감성 룩.',
    items: [
      { name: '카키 오버코트', emoji: '🧥', price: '₩149,000' },
      { name: '브라운 터틀넥', emoji: '🧶', price: '₩59,000' },
      { name: '코듀로이 팬츠', emoji: '👖', price: '₩69,000' },
      { name: '스웨이드 부츠', emoji: '🥾', price: '₩99,000' },
    ],
  },
  {
    id: 15, emoji: '🍁',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80',
    title: '체크 패턴 가을 룩', brand: 'Burberry', price: '₩385,000',
    season: '가을', style: '포멀', tags: ['체크', '포멀', '가을'],
    desc: '클래식 체크 패턴 블레이저와 슬랙스 조합. 세련되고 격식 있는 가을 룩.',
    items: [
      { name: '체크 블레이저', emoji: '🧥', price: '₩189,000' },
      { name: '그레이 슬랙스', emoji: '👖', price: '₩89,000' },
      { name: '터틀넥 이너', emoji: '👕', price: '₩49,000' },
      { name: '첼시 부츠', emoji: '🥾', price: '₩119,000' },
    ],
  },
  {
    id: 16, emoji: '🌰',
    image: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=400&q=80',
    title: '캐시미어 니트 룩', brand: 'Uniqlo', price: '₩189,000',
    season: '가을', style: '캐주얼', tags: ['캐시미어', '니트', '가을'],
    desc: '부드러운 캐시미어 니트와 데님 팬츠의 편안한 가을 룩. 주말 나들이에 딱.',
    items: [
      { name: '캐시미어 브이넥 니트', emoji: '🧶', price: '₩89,000' },
      { name: '슬림 데님', emoji: '👖', price: '₩59,000' },
      { name: '화이트 스니커즈', emoji: '👟', price: '₩49,000' },
    ],
  },
  {
    id: 17, emoji: '🦊',
    image: 'https://images.unsplash.com/photo-1600717448996-41d79571ee6e?w=400&q=80',
    title: '러스트 컬러 룩', brand: 'Mango', price: '₩172,000',
    season: '가을', style: '캐주얼', tags: ['러스트', '오렌지', '가을'],
    desc: '러스트 오렌지 컬러의 니트와 브라운 스커트. 가을 단풍처럼 따뜻한 색감의 룩.',
    items: [
      { name: '러스트 오버핏 니트', emoji: '🧶', price: '₩79,000' },
      { name: '브라운 미디 스커트', emoji: '👗', price: '₩59,000' },
      { name: '앵클 부츠', emoji: '🥾', price: '₩89,000' },
    ],
  },
  {
    id: 18, emoji: '🍄',
    image: 'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=400&q=80',
    title: '스트릿 가을 룩', brand: 'Stussy', price: '₩215,000',
    season: '가을', style: '스트릿', tags: ['스트릿', '후드', '가을'],
    desc: '오버핏 후드티와 카고 팬츠의 스트릿 가을 룩. 편하고 트렌디한 데일리 스타일.',
    items: [
      { name: '오버핏 후드 집업', emoji: '🧥', price: '₩89,000' },
      { name: '카고 팬츠', emoji: '👖', price: '₩79,000' },
      { name: '하이탑 스니커즈', emoji: '👟', price: '₩99,000' },
      { name: '비니', emoji: '🧢', price: '₩29,000' },
    ],
  },
  {
    id: 19, emoji: '❄️',
    image: 'https://images.unsplash.com/photo-1539533018257-f8e59d6c4984?w=400&q=80',
    title: '레이어드 겨울 룩', brand: 'Moncler', price: '₩389,000',
    season: '겨울', style: '캐주얼', tags: ['패딩', '겨울', '레이어드'],
    desc: '두꺼운 다운 재킷과 터틀넥의 조화. 따뜻하면서도 세련된 겨울 룩.',
    items: [
      { name: '다운 패딩', emoji: '🧥', price: '₩249,000' },
      { name: '터틀넥 니트', emoji: '🧶', price: '₩59,000' },
      { name: '조거 팬츠', emoji: '👖', price: '₩49,000' },
      { name: '어그 부츠', emoji: '🥾', price: '₩89,000' },
    ],
  },
  {
    id: 20, emoji: '🎄',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&q=80',
    title: '홀리데이 파티 룩', brand: 'Self-Portrait', price: '₩295,000',
    season: '겨울', style: '포멀', tags: ['파티', '홀리데이', '겨울'],
    desc: '반짝이는 시퀸 미디 드레스와 힐의 홀리데이 파티 룩. 크리스마스 파티에 완벽.',
    items: [
      { name: '시퀸 미디 드레스', emoji: '👗', price: '₩179,000' },
      { name: '스틸레토 힐', emoji: '👠', price: '₩89,000' },
      { name: '미니 클러치', emoji: '👛', price: '₩55,000' },
    ],
  },
  {
    id: 21, emoji: '☃️',
    image: 'https://images.unsplash.com/photo-1580913428023-02c695666d61?w=400&q=80',
    title: '코지 니트 룩', brand: 'Acne Studios', price: '₩312,000',
    season: '겨울', style: '미니멀', tags: ['코지', '니트', '겨울'],
    desc: '볼륨감 있는 오버핏 니트와 가죽 스커트의 조합. 세련되고 따뜻한 겨울 룩.',
    items: [
      { name: '벌키 오버핏 니트', emoji: '🧶', price: '₩159,000' },
      { name: '레더 미디 스커트', emoji: '👗', price: '₩99,000' },
      { name: '무릎 부츠', emoji: '🥾', price: '₩129,000' },
    ],
  },
  {
    id: 22, emoji: '🧊',
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=400&q=80',
    title: '모노크롬 겨울 룩', brand: 'COS', price: '₩268,000',
    season: '겨울', style: '미니멀', tags: ['모노크롬', '올블랙', '겨울'],
    desc: '올블랙 코디로 완성한 미니멀 겨울 룩. 심플하지만 강렬한 존재감.',
    items: [
      { name: '블랙 울 코트', emoji: '🧥', price: '₩149,000' },
      { name: '블랙 터틀넥', emoji: '👕', price: '₩49,000' },
      { name: '블랙 슬림 팬츠', emoji: '👖', price: '₩59,000' },
      { name: '블랙 첼시 부츠', emoji: '🥾', price: '₩119,000' },
    ],
  },
  {
    id: 23, emoji: '🏔️',
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=400&q=80',
    title: '아웃도어 겨울 룩', brand: 'The North Face', price: '₩425,000',
    season: '겨울', style: '스포티', tags: ['아웃도어', '등산', '겨울'],
    desc: '기능성 플리스와 테크 팬츠의 아웃도어 룩. 추운 날씨 야외 활동에 최적.',
    items: [
      { name: '고어텍스 자켓', emoji: '🧥', price: '₩229,000' },
      { name: '플리스 집업', emoji: '🧤', price: '₩89,000' },
      { name: '테크 팬츠', emoji: '👖', price: '₩79,000' },
      { name: '트레킹 부츠', emoji: '🥾', price: '₩149,000' },
    ],
  },
  {
    id: 24, emoji: '🌨️',
    image: 'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=400&q=80',
    title: '캐시미어 코트 룩', brand: 'Max Mara', price: '₩520,000',
    season: '겨울', style: '포멀', tags: ['코트', '캐시미어', '겨울'],
    desc: '클래식 카멜 캐시미어 코트와 부츠의 럭셔리 겨울 룩. 격식 있는 자리에 완벽.',
    items: [
      { name: '카멜 캐시미어 코트', emoji: '🧥', price: '₩329,000' },
      { name: '베이지 터틀넥', emoji: '🧶', price: '₩79,000' },
      { name: '슬랙스', emoji: '👖', price: '₩69,000' },
      { name: '무릎 부츠', emoji: '🥾', price: '₩129,000' },
    ],
  },
  {
    id: 25, emoji: '🎿',
    image: 'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&q=80',
    title: '스키 리조트 룩', brand: 'Moncler x CP Company', price: '₩580,000',
    season: '겨울', style: '스포티', tags: ['스키', '리조트', '겨울'],
    desc: '컬러풀한 스키복 스타일의 겨울 룩. 스키장이나 눈 내리는 날 스냅에 최고.',
    items: [
      { name: '스키복 재킷', emoji: '🧥', price: '₩289,000' },
      { name: '워터프루프 팬츠', emoji: '👖', price: '₩159,000' },
      { name: '스노우 부츠', emoji: '🥾', price: '₩129,000' },
      { name: '비니 + 장갑 세트', emoji: '🧤', price: '₩49,000' },
    ],
  },
  {
    id: 26, emoji: '🖤',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400&q=80',
    title: '올블랙 스트릿 룩', brand: 'Rick Owens', price: '₩445,000',
    season: '가을', style: '스트릿', tags: ['올블랙', '스트릿', '다크'],
    desc: '올블랙 스트릿 룩. 레이어드된 검은 의상들이 강렬한 존재감을 만들어냅니다.',
    items: [
      { name: '블랙 오버사이즈 재킷', emoji: '🧥', price: '₩189,000' },
      { name: '블랙 카고 팬츠', emoji: '👖', price: '₩109,000' },
      { name: '블랙 부츠', emoji: '🥾', price: '₩149,000' },
    ],
  },
  {
    id: 27, emoji: '🌙',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80',
    title: '야간 데이트 룩', brand: 'Toteme', price: '₩298,000',
    season: '봄', style: '포멀', tags: ['데이트', '나이트', '포멀'],
    desc: '새틴 슬립 드레스와 블레이저의 조합. 저녁 식사나 특별한 날 밤에 완벽한 룩.',
    items: [
      { name: '새틴 미디 드레스', emoji: '👗', price: '₩139,000' },
      { name: '오버핏 블레이저', emoji: '🧥', price: '₩109,000' },
      { name: '스트랩 힐', emoji: '👠', price: '₩89,000' },
    ],
  },
  {
    id: 28, emoji: '📚',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80',
    title: '캠퍼스 캐주얼 룩', brand: 'Champion x Carhartt', price: '₩145,000',
    season: '봄', style: '캐주얼', tags: ['캠퍼스', '대학생', '캐주얼'],
    desc: '후드티와 카고 팬츠, 스니커즈의 편안한 캠퍼스 룩. 강의실부터 도서관까지.',
    items: [
      { name: '챔피언 후드티', emoji: '👕', price: '₩59,000' },
      { name: '카하트 카고 팬츠', emoji: '👖', price: '₩79,000' },
      { name: '뉴발란스 스니커즈', emoji: '👟', price: '₩99,000' },
      { name: '백팩', emoji: '🎒', price: '₩49,000' },
    ],
  },
  {
    id: 29, emoji: '✈️',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    title: '여행 코디 룩', brand: 'Uniqlo x Muji', price: '₩128,000',
    season: '여름', style: '캐주얼', tags: ['여행', '편안함', '캐주얼'],
    desc: '편안하면서도 스타일리시한 여행 코디. 장시간 이동에도 구김 없이 깔끔함 유지.',
    items: [
      { name: '에어리즘 티셔츠', emoji: '👕', price: '₩25,000' },
      { name: '조거 팬츠', emoji: '👖', price: '₩39,000' },
      { name: '경량 집업', emoji: '🧥', price: '₩49,000' },
      { name: '슬립온 스니커즈', emoji: '👟', price: '₩45,000' },
    ],
  },
  {
    id: 30, emoji: '💼',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&q=80',
    title: '비즈니스 캐주얼 룩', brand: 'Brooks Brothers', price: '₩245,000',
    season: '봄', style: '포멀', tags: ['비즈니스', '출근', '캐주얼'],
    desc: '옥스퍼드 셔츠와 치노 팬츠의 스마트 캐주얼 룩. 격식과 편안함을 동시에.',
    items: [
      { name: '옥스퍼드 버튼다운 셔츠', emoji: '👔', price: '₩79,000' },
      { name: '치노 팬츠', emoji: '👖', price: '₩69,000' },
      { name: '로퍼', emoji: '🥿', price: '₩89,000' },
      { name: '레더 벨트', emoji: '👔', price: '₩35,000' },
    ],
  },
  {
    id: 31, emoji: '🎨',
    image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
    title: '아트 갤러리 룩', brand: 'Issey Miyake', price: '₩335,000',
    season: '봄', style: '미니멀', tags: ['아트', '미니멀', '개성'],
    desc: '구조적인 실루엣의 아방가르드 룩. 갤러리나 아트 이벤트에서 돋보이는 스타일.',
    items: [
      { name: '플리츠 블라우스', emoji: '👚', price: '₩149,000' },
      { name: '와이드 팬츠', emoji: '👖', price: '₩119,000' },
      { name: '플랫 뮬', emoji: '🥿', price: '₩79,000' },
    ],
  },
  {
    id: 32, emoji: '🏋️',
    image: 'https://images.unsplash.com/photo-1535530992830-e25d07cfa780?w=400&q=80',
    title: '애슬레저 룩', brand: 'Lululemon', price: '₩198,000',
    season: '여름', style: '스포티', tags: ['애슬레저', '운동', '스포티'],
    desc: '고기능성 레깅스와 스포츠 브라의 애슬레저 룩. 헬스장부터 브런치까지.',
    items: [
      { name: '하이웨이스트 레깅스', emoji: '🩱', price: '₩89,000' },
      { name: '스포츠 브라 탑', emoji: '👚', price: '₩59,000' },
      { name: '러닝화', emoji: '👟', price: '₩119,000' },
    ],
  },
  {
    id: 33, emoji: '🌵',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&q=80',
    title: '웨스턴 카우보이 룩', brand: "Levi's x Wrangler", price: '₩225,000',
    season: '가을', style: '빈티지', tags: ['웨스턴', '카우보이', '빈티지'],
    desc: '데님 재킷과 부츠컷 청바지의 웨스턴 룩. 페스티벌이나 야외 행사에 최고.',
    items: [
      { name: '데님 재킷', emoji: '🧥', price: '₩79,000' },
      { name: '부츠컷 청바지', emoji: '👖', price: '₩69,000' },
      { name: '웨스턴 부츠', emoji: '🥾', price: '₩119,000' },
      { name: '카우보이 햇', emoji: '🤠', price: '₩45,000' },
    ],
  },
  {
    id: 34, emoji: '🌹',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80',
    title: '페미닌 로맨틱 룩', brand: 'Zimmermann', price: '₩289,000',
    season: '봄', style: '캐주얼', tags: ['페미닌', '로맨틱', '봄'],
    desc: '러플 블라우스와 플로럴 미디 스커트의 로맨틱 룩. 봄 소풍이나 데이트에 완벽.',
    items: [
      { name: '러플 블라우스', emoji: '👚', price: '₩89,000' },
      { name: '플로럴 미디 스커트', emoji: '👗', price: '₩99,000' },
      { name: '끈 샌들', emoji: '👡', price: '₩59,000' },
      { name: '미니 버킷백', emoji: '👜', price: '₩69,000' },
    ],
  },
  {
    id: 35, emoji: '🎸',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80',
    title: '록 밴드 스트릿 룩', brand: 'Saint Laurent', price: '₩365,000',
    season: '가을', style: '스트릿', tags: ['록', '밴드', '스트릿'],
    desc: '가죽 재킷과 스키니 진의 록 스피릿 룩. 콘서트나 바에서 강렬한 인상.',
    items: [
      { name: '라이더 가죽 재킷', emoji: '🧥', price: '₩189,000' },
      { name: '블랙 스키니 진', emoji: '👖', price: '₩79,000' },
      { name: '앵클 부츠', emoji: '🥾', price: '₩109,000' },
      { name: '그래픽 티셔츠', emoji: '👕', price: '₩45,000' },
    ],
  },
  {
    id: 36, emoji: '🧘',
    image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&q=80',
    title: '요가 웰니스 룩', brand: 'Alo Yoga', price: '₩185,000',
    season: '봄', style: '스포티', tags: ['요가', '웰니스', '스포티'],
    desc: '플로우 팬츠와 요가 탑의 웰니스 룩. 요가 클래스부터 카페 브런치까지.',
    items: [
      { name: '플로우 요가 팬츠', emoji: '🩱', price: '₩89,000' },
      { name: '크롭 요가 탑', emoji: '👚', price: '₩59,000' },
      { name: '요가 매트백', emoji: '🎒', price: '₩45,000' },
    ],
  },
  {
    id: 37, emoji: '🌃',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80',
    title: '나이트 클럽 룩', brand: 'ASOS', price: '₩145,000',
    season: '여름', style: '스트릿', tags: ['클럽', '나이트', '파티'],
    desc: '메탈릭 탑과 미니스커트의 나이트 룩. 클럽이나 파티에서 빛나는 스타일.',
    items: [
      { name: '메탈릭 크롭탑', emoji: '👚', price: '₩45,000' },
      { name: '블랙 미니스커트', emoji: '👗', price: '₩39,000' },
      { name: '플랫폼 힐', emoji: '👠', price: '₩79,000' },
    ],
  },
  {
    id: 38, emoji: '🏡',
    image: 'https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=400&q=80',
    title: '홈 카페 룩', brand: 'Mango', price: '₩98,000',
    season: '겨울', style: '캐주얼', tags: ['홈카페', '코지', '겨울'],
    desc: '두꺼운 니트 카디건과 레깅스의 편안한 홈웨어 룩. 집에서도 스타일리시하게.',
    items: [
      { name: '오버핏 니트 카디건', emoji: '🧶', price: '₩59,000' },
      { name: '레깅스', emoji: '🩱', price: '₩29,000' },
      { name: '슬리퍼', emoji: '🩴', price: '₩19,000' },
    ],
  },
  {
    id: 39, emoji: '🎭',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80',
    title: '극장 포멀 룩', brand: 'Reiss', price: '₩312,000',
    season: '겨울', style: '포멀', tags: ['극장', '포멀', '클래식'],
    desc: '클래식한 블랙 수트와 화이트 셔츠. 연극, 오페라 등 격식 있는 문화행사에.',
    items: [
      { name: '블랙 수트 재킷', emoji: '🧥', price: '₩159,000' },
      { name: '블랙 수트 팬츠', emoji: '👖', price: '₩89,000' },
      { name: '화이트 드레스 셔츠', emoji: '👔', price: '₩55,000' },
      { name: '더비 슈즈', emoji: '👞', price: '₩119,000' },
    ],
  },
  {
    id: 40, emoji: '🌏',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    title: '백패커 여행 룩', brand: 'Patagonia', price: '₩235,000',
    season: '가을', style: '스포티', tags: ['백패킹', '여행', '아웃도어'],
    desc: '기능성 집업과 트레킹 팬츠의 백패커 룩. 어떤 날씨에도 대비할 수 있는 스타일.',
    items: [
      { name: '나일론 집업 재킷', emoji: '🧥', price: '₩99,000' },
      { name: '트레킹 팬츠', emoji: '👖', price: '₩79,000' },
      { name: '트레킹 부츠', emoji: '🥾', price: '₩129,000' },
      { name: '대용량 백팩', emoji: '🎒', price: '₩89,000' },
    ],
  },
];